mixed-port: 7890
tproxy-port: 7891
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: true
keep-alive-interval: 30
find-process-mode: strict
external-controller: "127.0.0.1:9090"
secret: "password-config"
external-ui: ui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
profile:
  store-selected: true
  store-fake-ip: false
unified-delay: true
tcp-concurrent: true
geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
geo-auto-update: true
geo-update-interval: 24
global-ua: clash.meta
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "cloudflare-ech.com"
    - "edge.microsoft.com"
  skip-domain:
    - "Mijia Cloud"
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  prefer-h3: true
  ipv6: true
  prefer-ipv6: true
  respect-rules: true
  use-hosts: true
  use-system-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "geosite:private,apple@cn,category-games@cn,cn":
      - 223.5.5.5
      - 119.29.29.29
    "geosite:google,geolocation-!cn,gfw":
      - https://cloudflare-dns.com/dns-query
      - tls://8.8.4.4
  proxy-server-nameserver:
    - https://cloudflare-dns.com/dns-query
    - 223.5.5.5
proxy-providers:
  mnc-instal:
    type: http
    url: my-subscription-address
    interval: 3600
    health-check:
      enable: true
      url: https://cp.cloudflare.com
      interval: 1800
proxy-groups:
  - {name: 🗽SELECT, type: select, include-all-providers: true, proxies: [🔥AUTO, DIRECT, 🇺🇸US, 🇭🇰HK, 🇸🇬SG, 🇹🇼TW, 🇯🇵JP,🇰🇷KR, 🇩🇪DE ]}
  - {name: 🛹OTHER, type: select, include-all-providers: true, proxies: [🗽SELECT, ➡️全球直连,🇺🇸US, 🇭🇰HK, 🇸🇬SG, 🇹🇼TW, 🇯🇵JP,🇰🇷KR, 🇩🇪DE  ]}
  - {name: 🌀Google, type: select, include-all-providers: true, proxies: [🗽SELECT,🇺🇸US, 🇭🇰HK, 🇸🇬SG, 🇹🇼TW, 🇯🇵JP,🇰🇷KR, 🇩🇪DE ]} 
  - {name: ⌨️OpenAI, type: select, include-all-providers: true, proxies: [🗽SELECT,🇺🇸US, 🇸🇬SG, 🇹🇼TW, 🇯🇵JP,🇰🇷KR, 🇩🇪DE ]}
  - {name: 📺YouTube, type: select, include-all-providers: true, proxies: [🗽SELECT,🇺🇸US, 🇭🇰HK, 🇸🇬SG, 🇹🇼TW, 🇯🇵JP,🇰🇷KR, 🇩🇪DE ]}
  - {name: 📱Telegram, type: select, include-all-providers: true, proxies: [🗽SELECT,🇺🇸US, 🇭🇰HK, 🇸🇬SG, 🇹🇼TW, 🇯🇵JP,🇰🇷KR, 🇩🇪DE  ]}
  - {name: 🗃OneDrive, type: select, include-all-providers: true,  proxies: [🗽SELECT,🇺🇸US, 🇭🇰HK, 🇸🇬SG, 🇹🇼TW, 🇯🇵JP,🇰🇷KR, 🇩🇪DE  ]}
  - {name: 🎮Games, type: select, include-all-providers: true,  proxies: [🗽SELECT, ➡️全球直连, 🇭🇰HK, ]}
  - {name: ➡️全球直连, type: select, proxies: [DIRECT, 🗽SELECT]}
  - {name: 🏴‍☠️全球拦截, type: select, proxies: [REJECT, 🗽SELECT, ➡️全球直连]}
  - {name: 🇭🇰HK, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇭🇰|HK|香港"}
  - {name: 🇹🇼TW, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇹🇼|TW|台湾"}
  - {name: 🇸🇬SG, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇸🇬|SG|新加坡"}
  - {name: 🇯🇵JP, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇯🇵|JP|日本"}
  - {name: 🇰🇷KR, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇰🇷|KR|韩国"}
  - {name: 🇺🇸US, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇺🇸|US|美国"}
  - {name: 🇬🇧UK, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇬🇧|UK|英国"}
  - {name: 🇩🇪DE, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇩🇪|DE|德国"}
  - {name: 🇫🇷FR, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇫🇷|FR|法国"}
  - {name: 🇨🇦CA, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇨🇦|CA|加拿大"}
  - {name: 🇦🇺AU, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "3000", timeout: "1000", filter: "🇦🇺|AU|澳大利亚"}
  - {name: 🔥AUTO, type: url-test, url: https://cp.cloudflare.com, include-all-providers: true, interval: "900", timeout: "500"}

rule-providers:
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
  - RULE-SET,lancidr,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,category-ads-all,🏴‍☠️全球拦截
  - PROCESS-NAME,sshd,➡️全球直连
  - PROCESS-NAME,ssh,➡️全球直连
  - DOMAIN-SUFFIX,recaptcha.net,🌀Google
  - DOMAIN-SUFFIX,googletagmanager.com,🌀Google
  - DOMAIN-SUFFIX,services.googleapis.cn,🌀Google
  - GEOSITE,openai,⌨️OpenAI
  - GEOSITE,onedrive,🗃OneDrive
  - GEOSITE,mega,🗃OneDrive
  - GEOSITE,microsoft,🗃OneDrive
  - GEOIP,telegram,📱Telegram
  - GEOSITE,telegram,📱Telegram
  - GEOSITE,discord,📱Telegram
  - GEOSITE,line,📱Telegram
  - GEOSITE,whatsapp,📱Telegram
  - GEOSITE,tiktok,📺YouTube
  - GEOSITE,youtube,📺YouTube
  - GEOSITE,netflix,📺YouTube
  - GEOSITE,disney,📺YouTube
  - GEOSITE,hbo,📺YouTube
  - GEOSITE,spotify,📺YouTube
  - GEOSITE,google,🌀Google
  - GEOSITE,oracle,🌀Google
  - GEOSITE,github,🌀Google
  - GEOSITE,gitlab,🌀Google
  - GEOSITE,reddit,🌀Google
  - GEOSITE,twitter,🌀Google
  - GEOSITE,cloudflare,🌀Google
  - GEOSITE,binance,🌀Google
  - GEOSITE,amazon,🗽SELECT
  - GEOSITE,meta,🗽SELECT
  - GEOSITE,apple,🗽SELECT
  - GEOSITE,speedtest,🗽SELECT
  - GEOSITE,docker,🗽SELECT
  - GEOSITE,steam,🎮Games
  - GEOSITE,epicgames,🎮Games
  - GEOSITE,blizzard,🎮Games
  - GEOSITE,ea,🎮Games
  - GEOSITE,ubisoft,🎮Games
  - GEOSITE,nintendo,🎮Games
  - GEOSITE,playstation,🎮Games
  - GEOSITE,xbox,🎮Games
  - GEOSITE,riot,🎮Games
  - GEOSITE,bytedance,➡️全球直连
  - GEOSITE,bilibili,➡️全球直连
  - GEOSITE,sina,➡️全球直连
  - GEOSITE,steam@cn,➡️全球直连
  - RULE-SET,applications,➡️全球直连
  - GEOSITE,gfw,🗽SELECT
  - GEOSITE,cn,➡️全球直连
  - GEOIP,CN,➡️全球直连
  - MATCH,🛹OTHER
